### ISSUE TITLE
When will be the next release?

### ISSUE THREAD

**Issue by jennyq** [epantry/django-sql-explorer#136]
We're using django-sql-explorer from master branch because the latest one on PyPI doesn't work with us. But we really hope you guys can push the latest update to PyPi as soon as possible so that we can explicitly specify the version.

Btw, this is a great app. We appreciate your work very much. Thanks!

**Comment by grantmcconnaughey** [comment]
One of our favorite third-party packages for Django. Looking forward to the release, also! :+1:

**Comment by chrisclark** [comment]
I will get a release done this week :) Thanks for the kind words!

**Comment by daneah** [comment]
Would love to get a release as well!

**Comment by chrisclark** [comment]
Holy moly I actually did it! 0.8.0 is up on PyPI. Let me know if you have questions, comments, concerns. Thanks all!

**Comment by jennyq** [comment]
Yeah! :+1:

**Comment by daneah** [comment]
Awesome! Thanks :smile:
