### ISSUE TITLE
Whitelist is compared to uppercase SQL query

### ISSUE THREAD

**Issue by jaymzcd** [epantry/django-sql-explorer#143]
Hello, first off thank you so much for this project - it's super useful! I noticed an issue with the way the whitelist is working. I have a table with a modified timestamp field named `updated`. If I add _updated_ to the `EXPLORER_SQL_WHITELIST` param within settings the query refuses to run and says it does not pass the blacklisting check. 

In [utils.py#L26](https://github.com/epantry/django-sql-explorer/blob/32aa6f7c0157f9a278f1f624bd039864b6e38223/explorer/utils.py#L26) the SQL query to run is transformed into all uppercase but the whitelist words are matched as they appear within the tuple. If I amend my tuple to have `('UPDATED', ...)` then the query passes and runs fine.

I am not sure what the best general fix for you would be - a simple one would be uppercasing the whitelist before the compare is done within `utils.py` but perhaps there is a reason for it matching exact case in this instance?

**Comment by chrisclark** [comment]
Thanks! That was just a regular ol' bug. Just fixed.
