### ISSUE TITLE
Text columns now export to CSV as bytestring representation

### ISSUE THREAD

**Issue by daneah** [epantry/django-sql-explorer#145]
Downloading a query result as CSV when using Python 3/MySQL now results in text columns being bytestrings, i.e. `b'Example'` rather than just `Example`.

1. Was this change intentional?
1. Is this configurable or is there a workaround? I thought of using transforms, but I don't think I'll be able to achieve what I'm looking to do.

**Comment by chrisclark** [comment]
It's a bug. Sorry. Will happily merge a pull request fixing it. I will get to it eventually, but can't promise anything within the next couple of days.

**Comment by daneah** [comment]
@chrisclark Thanks for the info. I was digging into it a bit but wasn't sure exactly what the best way forward might be. I'll try to take another look soon and I'll submit a PR if I work something up!
