### ISSUE TITLE
Blacklist is not enforced for Playground queries

### ISSUE THREAD

**Issue by Dimitri-Gnidash** [epantry/django-sql-explorer#162]

**Comment by chrisclark** [comment]
Geez, this is bad one. I heavily caveated the blacklist usage in the readme and encouraged use of a readonly sql connection...but that's no excuse. THANK YOU for finding this, as embarrassing as it is. Working on it now and will have a fix + release on Monday.

**Comment by Dimitri-Gnidash** [comment]
@chrisclark I understand. Thanks so much for picking this up :) :+1:

**Comment by flow-phys** [comment]
Thanks, for the great app @chrisclark !  We had disabled Playground for users but this would be great.
