### ISSUE TITLE
Hide snapshot features if not configured for S3

### ISSUE THREAD

**Issue by joelburton** [epantry/django-sql-explorer#172]
The snapshot feature in 0.8 requires S3 to store the results---but the checkbox offering to save the snapshot and the corresponding-but-broken snapshots table in the results are always present.

Can these be hidden if S3 is not configured?

**Comment by chrisclark** [comment]
This now inspects settings.EXPLORER_TASKS_ENABLED and hides the UI for email execution if False.

I thought this was a cleaner solution and in line with the fix for the email stuff.

Let me know if you disagree with the approach.

**Comment by chrisclark** [comment]
Also -- thanks for the issues!
