### ISSUE TITLE
Django 1.9 compatibility

### ISSUE THREAD

**Issue by FelixSebastianLange** [epantry/django-sql-explorer#175]
I get an error in the file explorer/utils.py, line 51:
*apps = [a for a in models.get_apps() if a.__package__ not in app_settings.EXPLORER_SCHEMA_EXCLUDE_APPS]*

The method *get_apps()* on django.db.models seems to be deprecated in 1.9 (cf. https://github.com/django-extensions/django-extensions/issues/661), but it's not obvious to me where it's substitute is.

This error shows once i click on the "Show Schema" button in the frontend.

**Comment by chrisclark** [comment]
I'm working on this issue in the 'deprecations' branch. You can run from there for now, until it's merged and released.
