### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by chrisclark** [epantry/django-sql-explorer#36]

**Comment by leebrooks0** [comment]
Hi

I am interested in adding Python3 compatibility. My boss said I could spend a day working on it, so before I do this, I just want to check that a) you would be interested in accepting a PR and that b) there are no hidden dragons preventing the upgrade. 

I am assuming that all I need to do is change to the new exception syntax etc and use some ```from futures import...``` as needed?

**Comment by chrisclark** [comment]
Hey Lee -- this sounds great! Definitely interested in a PR.

I don't have experience doing 2->3 ports, so can't speak to the work involved, but there shouldn't be any barriers. Explorer relies on 3 packages (Django, Factory Boy, and SQLparse), all of which are Python3 compatible.

Let me know if I can do anything to help. Feel free to ping me (chris@epantry.com) if you have any questions.
