### ISSUE TITLE
pip package for 0.6 missing south_migrations folder

### ISSUE THREAD

**Issue by jmanning2k** [epantry/django-sql-explorer#99]
This makes it incompatible with django-1.6.X as running syncdb raises the ImproperlyConfigured error in migrations/__init__.py.

The south_migrations folder exists under the git 0.6.0 tag, but is missing in the dist file.

**Comment by chrisclark** [comment]
Sorry about that. It's been fixed in master for a while. I will do a release today or tomorrow.

**Comment by chrisclark** [comment]
Also, thanks for reporting it!

**Comment by chrisclark** [comment]
I just released 0.7.0 which should resolve the issue.
